#!/bin/ash -x
UNBOUND_EXPORTER_HOST=${UNBOUND_EXPORTER_HOST:=tcp://localhost:8953}
UNBOUND_EXPORTER_CERT=${UNBOUND_EXPORTER_CERT:=}
UNBOUND_EXPORTER_KEY=${UNBOUND_EXPORTER_KEY:=}
UNBOUND_EXPORTER_CA=${UNBOUND_EXPORTER_CA:=}
UNBOUND_EXPORTER_LISTEN_ADDRESS=${UNBOUND_EXPORTER_LISTEN_ADDRESS:=}
UNBOUND_EXPORTER_TELEMETRY_PATH=${UNBOUND_EXPORTER_TELEMETRY_PATH:=}
UNBOUND_OPTIONS=""

if test \! -z "${UNBOUND_EXPORTER_HOST}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -unbound.host ${UNBOUND_EXPORTER_HOST}"
fi

if test \! -z "${UNBOUND_EXPORTER_CERT}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -unbound.cert ${UNBOUND_EXPORTER_CERT}"
fi

if test \! -z "${UNBOUND_EXPORTER_KEY}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -unbound.key ${UNBOUND_EXPORTER_KEY}"
fi

if test \! -z "${UNBOUND_EXPORTER_LISTEN_ADDRESS}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -web.listen-address ${UNBOUND_EXPORTER_LISTEN_ADDRESS}"
fi

if test \! -z "${UNBOUND_EXPORTER_CA}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -unbound.ca ${UNBOUND_EXPORTER_CA}"
fi

if test \! -z "${UNBOUND_EXPORTER_TELEMETRY_PATH}"; then
    UNBOUND_OPTIONS="${UNBOUND_OPTIONS} -web.telemetry-path ${UNBOUND_EXPORTER_TELEMETRY_PATH}"
fi

exec /app/unbound_exporter ${UNBOUND_OPTIONS} "$@"
