---
# tasks file for nut

- ansible.builtin.include_tasks:
    file: pod.yml
    apply:
      tags:
        - role::nut
        - role::nut:prepare
  tags:
    - role::nut
    - role::nut:prepare
- ansible.builtin.include_tasks:
    file: nut.yml
    apply:
      tags:
        - role::nut
        - role::nut:deploy
  tags:
    - role::nut
    - role::nut:deploy
- ansible.builtin.include_tasks:
    file: post.yml
    apply:
      tags:
        - role::nut
        - role::nut:post
  tags:
    - role::nut
    - role::nut:post
