---

- name: Create Network UPS Tools network
  containers.podman.podman_network:
    disable_dns: false
    ipv6: "{{ nut_network_ipv6 }}"
    name: "{{ nut_pod_name }}"
    state: present

- name: Create Network UPS Tools pod
  containers.podman.podman_pod:
    name: "{{ nut_pod_name }}"
    network: "{{ nut_pod_name }}"
    state: created
