---

- name: Create NUT exporter network
  containers.podman.podman_network:
    disable_dns: false
    ipv6: "{{ nut_exporter_network_ipv6 }}"
    name: "{{ nut_exporter_pod_name }}"
    state: present

- name: Create NUT exporter pod
  containers.podman.podman_pod:
    name: "{{ nut_exporter_pod_name }}"
    network: "{{ nut_exporter_pod_name }}"
    state: created
