---

- name: Generate systemd unit for NUT exporter pod
  containers.podman.podman_pod:
    network: "{{ nut_exporter_pod_name }}"
    name: "{{ nut_exporter_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __nut_exporter_systemd_path }}"
      restart_policy: always
  register: nut_exporter_service_unit_generate_result

- name: Run NUT exporter
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ nut_exporter_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"
