---

- name: Generate systemd unit for blackbox_exporter pod
  containers.podman.podman_pod:
    network: "{{ blackbox_exporter_pod_name }}"
    name: "{{ blackbox_exporter_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __blackbox_exporter_systemd_path }}"
      restart_policy: always
  register: blackbox_exporter_service_unit_generate_result

- name: Run blackbox_exporter pod
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ blackbox_exporter_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"
