---
# defaults file for nut_exporter

__nut_exporter_systemd_path: /etc/systemd/system
nut_exporter_pod_name: nut_exporter
nut_exporter_network_ipv6: true
nut_exporter_image_url: ghcr.io/druggeri/nut_exporter
nut_exporter_internal_listen_port: 9199
nut_exporter_external_listen_port: "{{ nut_exporter_internal_listen_port }}"
nut_exporter_ports_list:
  - "{{ nut_exporter_internal_listen_port }}:{{ nut_exporter_external_listen_port }}"
nut_exporter_health_check: "wget -S -T 2 -O - http://localhost:{{ nut_exporter_internal_listen_port }}"
nut_exporter_env_dict: {}
# nut_exporter_volume_list
