---

- name: Generate systemd unit for Prometheus pod
  containers.podman.podman_pod:
    network: "{{ prometheus_pod_name }}"
    name: "{{ prometheus_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __prometheus_systemd_path }}"
      restart_policy: always
  register: prometheus_service_unit_generate_result

- name: Run Prometheus pod
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ prometheus_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"
