---

- name: Create opnsense_exporter network
  containers.podman.podman_network:
    disable_dns: false
    ipv6: "{{ opnsense_exporter_network_ipv6 }}"
    name: "{{ opnsense_exporter_pod_name }}"
    state: present

- name: Create opnsense_exporter pod
  containers.podman.podman_pod:
    name: "{{ opnsense_exporter_pod_name }}"
    network: "{{ opnsense_exporter_pod_name }}"
    state: created
