---

- name: Generate systemd unit for opnsense_exporter pod
  containers.podman.podman_pod:
    network: "{{ opnsense_exporter_pod_name }}"
    name: "{{ opnsense_exporter_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __opnsense_exporter_systemd_path }}"
      restart_policy: always
  register: opnsense_exporter_service_unit_generate_result

- name: Run opnsense_exporter pod
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ opnsense_exporter_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"

