---

- name: Generate systemd unit for keepalived_vrrp pod
  containers.podman.podman_pod:
    network: "{{ keepalived_vrrp_pod_name }}"
    name: "{{ keepalived_vrrp_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __keepalived_vrrp_systemd_path }}"
      restart_policy: always
  register: keepalived_vrrp_service_unit_generate_result

- name: Run keepalived_vrrp pod
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ keepalived_vrrp_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"

