---

- name: Generate systemd unit for Grafana
  containers.podman.podman_pod:
    network: "{{ grafana_pod_name }}"
    name: "{{ grafana_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: "{{ __grafana_systemd_path }}"
      restart_policy: always
  register: grafana_service_unit_generate_result

- name: Run Grafana pod
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ grafana_service_unit_generate_result['podman_systemd'].keys() | flatten(1) }}"

