---
# defaults file for opnsense-exporter
__opnsense_exporter_config_dir: /etc/opnsense_exporter
__opnsense_exporter_systemd_path: /etc/systemd/system
__opnsense_exporter_service_unit_container_prefix: container-
__opnsense_exporter_service_unit_pod_prefix: pod-

opnsense_exporter_instance: "{{ inventory_hostname }}:{{ opnsense_exporter_external_listen_port }}"
opnsense_exporter_pod_name: opnsense_exporter
opnsense_exporter_instance_name: opnsense_exporter
opnsense_exporter_network_ipv6: true
opnsense_exporter_image_url: ghcr.io/athennamind/opnsense-exporter:latest
opnsense_exporter_internal_listen_port: 14237
opnsense_exporter_external_listen_port: "{{ opnsense_exporter_internal_listen_port }}"
opnsense_exporter_ports_list: []
opnsense_exporter_launch_command_list:
  - "--web.listen-address=:{{ opnsense_exporter_internal_listen_port }}"
opnsense_exporter_env_dict: {}
opnsense_exporter_network_list:
  - "{{ opnsense_exporter_pod_name }}"
opnsense_exporter_secrets_list:
  - name: OPNSENSE_EXPORTER_OPS_API
    data: supersecret99
    skip_existing: true
    force: false
  - name: OPNSENSE_EXPORTER_OPS_API_KEY
    data: ey/hunter2
