---
# handlers file for prometheus

- name: Reload Prometheus
  delegate_to: localhost
  become: false
  ansible.builtin.uri:
    method: POST
    url: "http://{{ inventory_hostname }}:{{ prometheus_external_listen_port }}/-/reload"
  listen:
    - Reload Prometheus
