---

- name: Create Prometheus network
  containers.podman.podman_network:
    disable_dns: false
    ipv6: "{{ prometheus_network_ipv6 }}"
    name: "{{ prometheus_pod_name }}"
    state: present

- name: Create Prometheus pod
  containers.podman.podman_pod:
    name: "{{ prometheus_pod_name }}"
    network: "{{ prometheus_pod_name }}"
    state: created
