---

- name: Generate systemd unit for Prometheus pod
  containers.podman.podman_pod:
    network: "{{ prometheus_pod_name }}"
    name: "{{ prometheus_pod_name }}"
    state: created
    generate_systemd:
      names: true
      path: /etc/systemd/system
      restart_policy: always

- name: Run Prometheus pod
  ansible.builtin.service:
    name: "pod-{{ prometheus_pod_name }}"
    state: started
    enabled: true
    daemon_reload: true
