---
# handlers file for keepalived_vrrp

- name: Reload keepalived
  ansible.builtin.command:
    cmd: podman kill --signal HUP "{{ keepalived_vrrp_pod_name }}-keepalived_vrrp"
  listen: Reload keepalived_vrrp
