---
# handlers file for blackbox_exporter
- name: Reload blackbox_exporter
  ansible.builtin.uri:
    method: POST
    url: "http://{{ ansible_default_ipv6['address'] | default(ansible_default_ipv4['address']) }}:{{ blackbox_exporter_external_listen_port }}/-/reload"
  listen:
    - Reload blackbox_exporter
