---
# handlers file for blackbox_exporter
- name: Reload blackbox_exporter
  ansible.builtin.uri:
    method: POST
    url: "http://{{ inventory_hostname }}:{{ blackbox_exporter_external_listen_port }}/-/reload"
  listen:
    - Reload blackbox_exporter
