---
# handlers file for blackbox_exporter
- name: Reload blackbox_exporter
  ansible.builtin.uri:
    method: POST
    url: "http://{{ blackbox_exporter_instance }}/-/reload"
  listen:
    - Reload blackbox_exporter
